### PR TITLE
Remove globalconfig and cleaned up styling in a few files

### PR DESCRIPTION
**Pull request by bowbahdoe**
The globalconfig class isn't necessary. Patterns like the singleton pattern only really make sense
in the context of a statically typed language like Java and don't really apply in Python.

The `copyConfig` methods as written in the MetricInfo classes would break whenever called since they do not use self to get instance variables. Since they must be unused and they are broken I just removed them.

### CODE REVIEW

**Comment by bowbahdoe** [comment]
Yes, of course. This repository disappeared from Github for awhile so I assumed that it was being taken back to being internal. That's why the repository this was PRed from is gone. I'll fix that promptly. 

I'll write some unit tests for what I can in this branch, though some things are not really testable, such as removing the copyConfig methods, without other tests existing for the rest of the codebase.

**Comment by pzou1974** [comment]
We added travis ci integration. Please check pytest sample under tests .  We will start from there. Again. Thank you so much to contribute ,

**Comment by bowbahdoe** [comment]
Resolving the missing repo issue turned out to be a bit of a headache so I will close this PR and reopen when I have some tested changes from a fresh fork

**Comment by pzou1974** [comment]
sounds good. But again usually we will store GlobalConfig on Singlton object which is what I did.  I do not fell anything wrong with it.

**Pull request closed without merging**
